/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */

public class home extends javax.swing.JFrame {

      DBhandler db= new DBhandler();
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
         setExtendedState(getExtendedState() | this.MAXIMIZED_BOTH);
         db.CurrentDate(txttime);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txttime = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonstock = new javax.swing.JButton();
        buttonvendor = new javax.swing.JButton();
        buttoncustomers = new javax.swing.JButton();
        buttonuser = new javax.swing.JButton();
        buttonsale = new javax.swing.JButton();
        buttonlogout = new javax.swing.JButton();
        buttonexpenses = new javax.swing.JButton();
        buttonreports = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADEEL MEDICAL STORE");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/logout.png"))); // NOI18N
        jLabel1.setText("logout");
        jLabel1.setToolTipText("logout");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1220, 590, 80, 90);

        txttime.setEditable(false);
        getContentPane().add(txttime);
        txttime.setBounds(1120, 20, 210, 33);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(null);

        buttonstock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/stock32.png"))); // NOI18N
        buttonstock.setText("Stock");
        buttonstock.setToolTipText("Manage Stock");
        buttonstock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonstock.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonstockActionPerformed(evt);
            }
        });
        jPanel1.add(buttonstock);
        buttonstock.setBounds(30, 30, 190, 150);

        buttonvendor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonvendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/vendors2.png"))); // NOI18N
        buttonvendor.setText("Vendors");
        buttonvendor.setToolTipText("Vendors");
        buttonvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonvendorActionPerformed(evt);
            }
        });
        jPanel1.add(buttonvendor);
        buttonvendor.setBounds(510, 30, 190, 150);

        buttoncustomers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttoncustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/Customer.png"))); // NOI18N
        buttoncustomers.setText("Customers");
        buttoncustomers.setToolTipText("Customers");
        buttoncustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncustomersActionPerformed(evt);
            }
        });
        jPanel1.add(buttoncustomers);
        buttoncustomers.setBounds(750, 30, 190, 150);

        buttonuser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/users2.png"))); // NOI18N
        buttonuser.setText("Users");
        buttonuser.setToolTipText("Users");
        buttonuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonuserActionPerformed(evt);
            }
        });
        jPanel1.add(buttonuser);
        buttonuser.setBounds(30, 220, 190, 150);

        buttonsale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonsale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/sale2.png"))); // NOI18N
        buttonsale.setText("Sales");
        buttonsale.setToolTipText("Sales");
        buttonsale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsaleActionPerformed(evt);
            }
        });
        jPanel1.add(buttonsale);
        buttonsale.setBounds(270, 30, 190, 150);

        buttonlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/logout.png"))); // NOI18N
        buttonlogout.setText("Logout");
        buttonlogout.setToolTipText("Logout");
        buttonlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(buttonlogout);
        buttonlogout.setBounds(750, 220, 190, 150);

        buttonexpenses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonexpenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/expenses1.png"))); // NOI18N
        buttonexpenses.setText("Expenses");
        buttonexpenses.setToolTipText("Expenses");
        buttonexpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonexpensesActionPerformed(evt);
            }
        });
        jPanel1.add(buttonexpenses);
        buttonexpenses.setBounds(510, 220, 190, 150);

        buttonreports.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/reports2.png"))); // NOI18N
        buttonreports.setText("Reports");
        buttonreports.setToolTipText("Reports");
        buttonreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonreportsActionPerformed(evt);
            }
        });
        jPanel1.add(buttonreports);
        buttonreports.setBounds(270, 220, 190, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 150, 970, 400);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Manage Stock");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Manage Sales");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("New Sale");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Manage Vendors");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Manage Customers");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Manage Users");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Manage Reports");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Manage Expenses");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Exit");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonvendorActionPerformed
      
        vendors f= new vendors ();
        f.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_buttonvendorActionPerformed

   
    private void buttonstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonstockActionPerformed

            stock f= new stock();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_buttonstockActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Log Out ?", "EXIT ?",JOptionPane.YES_NO_OPTION);
          if (showConfirmDialog==0)
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
  
          
    }//GEN-LAST:event_jLabel1MouseClicked

    private void buttonsaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsaleActionPerformed
        Sales f= new Sales();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonsaleActionPerformed

    private void buttoncustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncustomersActionPerformed
            customers f= new customers();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_buttoncustomersActionPerformed

    private void buttonuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonuserActionPerformed
            users f= new users();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_buttonuserActionPerformed

    private void buttonreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonreportsActionPerformed
            reports f= new  reports();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_buttonreportsActionPerformed

    private void buttonexpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonexpensesActionPerformed
            expenses f= new  expenses();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_buttonexpensesActionPerformed

    private void buttonlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlogoutActionPerformed
         int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Logout ?", "EXIT ?",JOptionPane.YES_NO_OPTION);
          if (showConfirmDialog==0)
             // dispose();
              dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_buttonlogoutActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
            customers f= new customers();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
            stock f= new stock();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         Sales f= new Sales();
         f.setVisible(true);
         dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         vendors f= new vendors ();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         newsale f= new newsale ();
         f.setVisible(true);
         dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
            users f= new users();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
            reports f= new  reports();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
            expenses f= new  expenses();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Logout ?", "EXIT ?",JOptionPane.YES_NO_OPTION);
          if (showConfirmDialog==0)
             dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
  
    }//GEN-LAST:event_jMenuItem8ActionPerformed

     public static void main(String args[]) {
         
          try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
          
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
        
     }
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncustomers;
    private javax.swing.JButton buttonexpenses;
    private javax.swing.JButton buttonlogout;
    private javax.swing.JButton buttonreports;
    private javax.swing.JButton buttonsale;
    private javax.swing.JButton buttonstock;
    private javax.swing.JButton buttonuser;
    private javax.swing.JButton buttonvendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
