/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author dell
 */
public class updatecustomer extends javax.swing.JFrame {
    DBhandler db= new DBhandler();
    /**
     * Creates new form updatecustomer
     */
    public updatecustomer() {
        initComponents();
         setExtendedState(getExtendedState() | this.MAXIMIZED_BOTH);
        db.updatetable("customer", jTable1);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        contact = new javax.swing.JTextField();
        searchtxt = new javax.swing.JTextField();
        adress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        blnc = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updatebutton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        idfield = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPDATE CUSTOMER");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/back.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel1.setLayout(null);

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel1.add(contact);
        contact.setBounds(220, 440, 275, 33);

        searchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtActionPerformed(evt);
            }
        });
        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
        });
        jPanel1.add(searchtxt);
        searchtxt.setBounds(350, 10, 530, 33);

        adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressActionPerformed(evt);
            }
        });
        jPanel1.add(adress);
        adress.setBounds(600, 350, 275, 33);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 16));
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Search by  :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 107, 33);

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, 16));
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Contact No:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 440, 96, 20);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD, 16));
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Address  :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 350, 81, 20);

        blnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blncActionPerformed(evt);
            }
        });
        jPanel1.add(blnc);
        blnc.setBounds(600, 390, 275, 33);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"ID","Customer_Name"
            , "Contact_No","Address","Total_Borrow" }));
jPanel1.add(jComboBox1);
jComboBox1.setBounds(170, 10, 157, 31);

jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
    }
    });
    jScrollPane1.setViewportView(jTable1);

    jPanel1.add(jScrollPane1);
    jScrollPane1.setBounds(70, 60, 810, 280);

    jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() | java.awt.Font.BOLD, 16));
    jLabel8.setForeground(new java.awt.Color(0, 153, 153));
    jLabel8.setText("Borrow  :");
    jPanel1.add(jLabel8);
    jLabel8.setBounds(510, 400, 75, 20);

    jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD, 16));
    jLabel7.setForeground(new java.awt.Color(0, 153, 153));
    jLabel7.setText("Customer Name:");
    jPanel1.add(jLabel7);
    jLabel7.setBounds(70, 400, 144, 20);

    updatebutton1.setText("Update");
    updatebutton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            updatebutton1ActionPerformed(evt);
        }
    });
    jPanel1.add(updatebutton1);
    updatebutton1.setBounds(570, 500, 298, 34);

    jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() | java.awt.Font.BOLD, 16));
    jLabel9.setForeground(new java.awt.Color(0, 153, 153));
    jLabel9.setText("ID:");
    jPanel1.add(jLabel9);
    jLabel9.setBounds(70, 350, 65, 20);

    cname.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cnameActionPerformed(evt);
        }
    });
    jPanel1.add(cname);
    cname.setBounds(220, 390, 275, 33);

    idfield.setEditable(false);
    idfield.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            idfieldActionPerformed(evt);
        }
    });
    jPanel1.add(idfield);
    idfield.setBounds(220, 350, 275, 33);

    updatebutton.setText("Update");
    updatebutton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            updatebuttonActionPerformed(evt);
        }
    });
    jPanel1.add(updatebutton);
    updatebutton.setBounds(200, 500, 298, 34);

    jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/stock32.png"))); // NOI18N
    jLabel11.setToolTipText("Stock");
    jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel11MouseClicked(evt);
        }
    });

    jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/sale2.png"))); // NOI18N
    jLabel12.setToolTipText("Sales");
    jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel12MouseClicked(evt);
        }
    });

    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/vendors2.png"))); // NOI18N
    jLabel13.setToolTipText("Distributors");
    jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel13MouseClicked(evt);
        }
    });

    jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/Customer.png"))); // NOI18N
    jLabel14.setToolTipText("Customers");
    jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel14MouseClicked(evt);
        }
    });

    jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/users2.png"))); // NOI18N
    jLabel15.setToolTipText("Users");
    jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel15MouseClicked(evt);
        }
    });

    jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/reports2.png"))); // NOI18N
    jLabel16.setToolTipText("Reports");
    jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel16MouseClicked(evt);
        }
    });

    jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/expenses1.png"))); // NOI18N
    jLabel17.setToolTipText("Expenses");
    jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel17MouseClicked(evt);
        }
    });

    jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/about.png"))); // NOI18N
    jLabel18.setToolTipText("About Software");
    jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel18MouseClicked(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(310, 310, 310)
            .addComponent(jLabel11)
            .addGap(18, 18, 18)
            .addComponent(jLabel12)
            .addGap(18, 18, 18)
            .addComponent(jLabel13)
            .addGap(18, 18, 18)
            .addComponent(jLabel14)
            .addGap(18, 18, 18)
            .addComponent(jLabel15)
            .addGap(18, 18, 18)
            .addComponent(jLabel16)
            .addGap(18, 18, 18)
            .addComponent(jLabel17)
            .addGap(18, 18, 18)
            .addComponent(jLabel18)
            .addContainerGap(379, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(55, 55, 55)
            .addComponent(jLabel2)
            .addGap(138, 138, 138)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE))))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int i= jTable1.getSelectedRow();
        TableModel model= jTable1.getModel();
        String id =model.getValueAt(i, 0).toString();
        idfield.setText(id);
        cname.setText(model.getValueAt(i, 1).toString());
        contact.setText(model.getValueAt(i, 2).toString());
        adress.setText(model.getValueAt(i, 3).toString());
        blnc.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void searchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxtActionPerformed

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        String temp=searchtxt.getText()+"%";
        Object type=jComboBox1.getSelectedItem();
        //JOptionPane.showMessageDialog(null, type);
        String sql="select * from customer where "+ type+" like'"+temp+"'";
        db.executeResult(sql);
        jTable1.setModel(DbUtils.resultSetToTableModel(db.rs));
    }//GEN-LAST:event_searchtxtKeyReleased

    private void adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressActionPerformed

    private void blncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blncActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed

        String name= cname.getText();
        String contact1= contact.getText();
        String adres1= adress.getText();
        String blnc1= blnc.getText();
        String id= idfield.getText();
        
        if( name.isEmpty()||contact1.isEmpty()||adres1.isEmpty()||blnc1.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please Fill All The Fields !");
        
        }
        else {
            
        String sql="update customer set Customer_Name='"+name+"',Contact_No='"+contact1+"',address='"+adres1
        +"',Total_Borrow='"+blnc1+"' where id ="+id;

        db.executequery(sql, "Updated");
        cname.setText("");
        contact.setText("");
        adress.setText("");
        blnc.setText("");
        idfield.setText("");
        db.updatetable("customer", jTable1);
        }
   
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        customers f= new customers();
        f.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel2MouseClicked

    private void updatebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebutton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        stock f= new stock();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        Sales f= new Sales();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        vendors f= new vendors ();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        customers f= new customers();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        users f= new users();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        reports f= new  reports();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        expenses f= new  expenses();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This Software is Developed by Conlite Solutions\n Managed By Waqar Ahmed 0304-7203271\n"
            + "This product is licensed To ADEEL MEDICAL STORE \n LICENSE NO :901-001");
    }//GEN-LAST:event_jLabel18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatecustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adress;
    private javax.swing.JTextField blnc;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField idfield;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JButton updatebutton;
    private javax.swing.JButton updatebutton1;
    // End of variables declaration//GEN-END:variables
}
